apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: stg-
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 7.7.3
    releaseName: argocd
    namespace: argocd
    includeCRDs: true
    valuesFile: values.yaml
