apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: prd-
helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 8.6.4
    releaseName: grafana
    namespace: grafana
    includeCRDs: true
    valuesFile: grafana-values.yaml
