apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: uat-
helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.29.1
    namespace: vault
    includeCRDs: true
    valuesFile: values.yaml
